### ISSUE TITLE
Running bcrypt alongside JIT causing server crash

### ISSUE THREAD

**Issue by xunder-matth** [Sreyas-Sreelal/samp-bcrypt#14]
As the title says, trying to run this plugin alongside [JIT Plugin](https://github.com/Zeex/samp-plugin-jit) is causing the server to crash on startup.

```
[log-core] fatal signal '11' (SIGSEGV) watched  
```

logs/log-core.log

```
[10/26/21 20:45:21] [ERROR] signal 11 (SIGSEGV) catched; shutting log-core down (errno: 0, signal code: 128, exit status: 0)
```

**Comment by Sreyas-Sreelal** [comment]
Hey sorry for late reply. It is loading fine for me. Could you check if you're using any other plugins or could you provide a MVCE ?

**Comment by xunder-matth** [comment]
Looks like it was very specific case issue and I'm unable do reproduce it right now. I'll reopen this issue if I find a way to reproduce it.
