### ISSUE TITLE
bcrypt_hash callback does not called if the filterscript was reloaded

### ISSUE THREAD

**Issue by kalacsparty** [Sreyas-Sreelal/samp-bcrypt#18]
I’m using my mode as a filterscript for testing reasons. If I start the server it’s fine until I reload the script. When I reload it the callback won’t get called.

**Comment by Sreyas-Sreelal** [comment]
Hey sorry for late reply. Could you please provide a MVCE ? I wasn't able to reproduce this issue.

**Comment by Sreyas-Sreelal** [comment]
Closing this issue since there was no response.
