### ISSUE TITLE
OnDialogResponse

### ISSUE THREAD

**Issue by Victe221** [Sreyas-Sreelal/samp-bcrypt#19]
Doesn't work with inputtext in OnDialogResponse or it is just me?

new hash[BCRYPT_HASH_LENGTH];
printf("%s", inputtext);
            
bcrypt_hash(playerid, "OnPasswordHash", inputtext, BCRYPT_COST);
            
format(hash, 65, "%s", bcrypt_get_hash(hash));
printf("1: %s", bcrypt_get_hash(hash));
printf("2: %s", hash);

printf with inputtext shows player's password
printf 1 null
printf 2 null

**Comment by burridgedan** [comment]
I am going to assume the above code is all within the dialog response callback as that's how you have shown it here. With the bcrypt_hash and bcrypt_verify functions you need to pass the result to a callback to handle the result.

Under your dialog response:

```Pawn
bcrypt_hash(playerid, "OnPasswordHash", inputtext, BCRYPT_COST);
```

Under a public function called "OnPasswordHash"

```Pawn
forward OnPassswordHash(playerid);
public OnPassswordHash(playerid)
{
    new hash[BCRYPT_HASH_LENGTH];
    format(hash, 65, "%s", bcrypt_get_hash(hash));
    printf("1: %s", bcrypt_get_hash(hash));
    printf("2: %s", hash);
}
```

Look at the main README file for more examples.

**Comment by Victe221** [comment]
Hmm. function OnPasswordHash doesn't work(zero call, no printfs) I don't know why. Plugin bcrypt loaded correctly: 
[16:37:31] [Info] Loading plugin: samp_bcrypt
[16:37:31] [Info] [SampBcrypt] [info]: Version: 0.3.4

Also I tried: bcrypt_hash(playerid, "OnPasswordHash", "password1", BCRYPT_COST); In OnGameModeInit but still zero call, no printfs. 

I'm using open.mp not samp so maybe here's problem? I don't know 🌵

**Comment by Victe221** [comment]
Okay. I fixed it. Problem was with spacebar, fix: bcrypt_hash(playerid,"OnPassswordHash",inputtext,BCRYPT_COST);

Omg 🍡
