### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by nekjutsu** [Sreyas-Sreelal/samp-bcrypt#21]
WARN: failed to ensure plugin github.com/Sreyas-Sreelal/samp-bcrypt:0.4.0 failed to get plugin github.com/Sreyas-Sreelal/samp-bcrypt:0.4.0 from net: resource matcher 'samp-bcrypt-windows-x86.zip' does not match any release assets from '[ samp-bcrypt-linux-x86.zip samp_bcrypt-windows-x86.zip]'

Rename please

Funny that [this project](https://github.com/bmisiak/samp-precise-timers) has a similar problem :)

**Comment by Sreyas-Sreelal** [comment]
Thank you. I've renamed the release binaries now.

**Comment by nekjutsu** [comment]
It works. Thanks for the quick response and problem solving
