### ISSUE TITLE
Unable to Load in Linux

### ISSUE THREAD

**Issue by AtlanticCityRoleplay** [Sreyas-Sreelal/samp-bcrypt#22]
Loading plugin: samp_bcrypt.so
  Failed (/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by plugins/samp_bcrypt.so))

**Comment by Sreyas-Sreelal** [comment]
Either upgrade your glibc in your OS or recompile the plugin in your own OS
