### ISSUE TITLE
SAMPCTL

### ISSUE THREAD

**Issue by Bronzal** [Sreyas-Sreelal/samp-bcrypt#3]
WARN: failed to ensure package github.com/Sreyas-Sreelal/samp-bcrypt:0.2.2: failed to ensure dependency from cache: remote repository is empty

WARN: failed to ensure package github.com/Sreyas-Sreelal/samp-bcrypt: failed to ensure dependency from cache: remote repository is empty

ensuring from .json or via sampctl p install - doesn't work

**Comment by Bronzal** [comment]
can be fixed by deleting .samp folder from user files

**Comment by ADRFranklin** [comment]
I didn't say delete the `.samp` folder, I said delete the package called `Sreyas-Sreelal/samp-bcrypt`, located inside the `.samp/packages` folder and it will re-download it.

There was no need to have to delete all of it, and have time, resources and bandwidth wasted re-downloading your entire projects dependencies again.

**Comment by Bronzal** [comment]
@ADRFranklin Actually I've tried to only delete samp-bcrypt but came up with same warning, removing the folder helped for me.

Resources and bandwidth? funny :D
