### ISSUE TITLE
sampctl...

### ISSUE THREAD

**Issue by tr1xy** [Sreyas-Sreelal/samp-bcrypt#5]
Please release the const corrected version or fix it somehow inside pawn.json cuz SAMPCTL users still get `(warning) literal array/string passed to a non-const parameter`

**Comment by tr1xy** [comment]
Actually, removing the version (:0.2.2) tag and reinstall it and then again adding the version tag seems to be working...

**Comment by Sreyas-Sreelal** [comment]
those who having the issue make sure that you re-ensure the packages

**Comment by tr1xy** [comment]
The problem is that it was a clear install :D
