### ISSUE TITLE
Create an another release

### ISSUE THREAD

**Issue by omcho420** [Sreyas-Sreelal/samp-bcrypt#6]
If u could please add an release with #4 since every time we download a new dependencie we have to manually update the .inc file for bcyrpt

**Comment by Sreyas-Sreelal** [comment]
You don't have to update .inc every time.It might be probably due to the existing include in the cache of sampctl is being not updated.Try installing the package in a complete new project,it'll fetch the latest.
or remove the cache and re ensure the package
```bash
rm -rf ~/.samp/packages/sreyas-sreelal/sampbcrypt/
```
and on your project

```bash
sampctl p ensure
```

**Comment by omcho420** [comment]
I totally forgot about the versioning system, since I specified a version '0.2.2' it didn't download the newest .inc file

If anyone still get's 'const' warrnings just remove the s specified version in pawn.json
