### ISSUE TITLE
Not backwards compatible

### ISSUE THREAD

**Issue by Y-Less** [Sreyas-Sreelal/samp-bcrypt#7]
The new release adds optional parameters to the callback (not debating the usefulness of this here).  However, while the format specifier is optional in the include, it is required in the plugin.  This means you can't just swap out the plugin and use an existing mode with it; you are forced to recompile.  Probably not a problem for most people, but the fifth argument should be optional in the plugin as well.

**Comment by fababel** [comment]
`[SampBcrypt] [error]: The argument count mismatch expected :12 provided: 4294967295.`

y_inline + bcrypt has broke just now for lastest released.

**Comment by Y-Less** [comment]
Did you recompile your mode?  This was exactly the problem I was talking about.

**Comment by Sreyas-Sreelal** [comment]
Sorry for the delay. I have fixed the issue in 7b549d9 thanks :). I'll make a new patch after doing some more tests
