### ISSUE TITLE
Cannot execute callback

### ISSUE THREAD

**Issue by mrreus** [Sreyas-Sreelal/samp-bcrypt#8]
I currently use the newest version (0.3.2). Tested this on Windows 10.

```
main()
{
	bcrypt_hash(0, "testCallback", "password", 12);
}

forward testCallback(playerid);
public testCallback(playerid)
{
	new string[200];
	bcrypt_get_hash(string);

	print(string);
}
```

server_log.txt:
```
[SampBcrypt] [error]: *Cannot execute callback "testCallback"
$2y$12$lPesaPOT0fgPNOmIIboCS.DJxpJDT2rTVZpwfNjnj0.038Xeb2dBu
```

**Comment by Sreyas-Sreelal** [comment]
I can't seem to reproduce this issue..It's working fine for me.  Seems in your case the callback is executed correctly but still the error pops up..Can you make sure you're using 0.3.2 include and plugin ?

Edit: Apparently this occurs when server is loaded with more than one AMX instances and plugin continues it's search for callback in all these AMX instances even after successfully executing it. I will make a adjustment to 0.3.2 and reupload the binary with this tiny fix, Thank you :)
